/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Varnoika Mujumdar
 */
public class CreatePersonJPanel extends javax.swing.JPanel {
    
   JPanel userProcessContainer;
   PersonDirectory personDirectory;

    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        this.userProcessContainer=container;
        this.personDirectory=directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workAddressJPanel = new javax.swing.JPanel();
        lblHomeAddressTitle = new javax.swing.JLabel();
        lblHomeStreetAddress = new javax.swing.JLabel();
        txtHomeAddress = new javax.swing.JTextField();
        lblHomeUnitNumber = new javax.swing.JLabel();
        txtHomeUnitNumber = new javax.swing.JTextField();
        lblHomeCity = new javax.swing.JLabel();
        txtHomeCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtHomeState = new javax.swing.JTextField();
        lblHomeZipCode = new javax.swing.JLabel();
        txtHomeZipCode = new javax.swing.JTextField();
        lblHomePhoneNumber = new javax.swing.JLabel();
        txtHomePhoneNumber = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblfirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblBMI = new javax.swing.JLabel();
        txtBMI = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        homeAddressJPanel1 = new javax.swing.JPanel();
        lblAddressTitle1 = new javax.swing.JLabel();
        lblStreetAddress1 = new javax.swing.JLabel();
        txtStreetAddress1 = new javax.swing.JTextField();
        lblUnitNumber1 = new javax.swing.JLabel();
        txtUnitNumber1 = new javax.swing.JTextField();
        lblCity1 = new javax.swing.JLabel();
        txtCity1 = new javax.swing.JTextField();
        lblState1 = new javax.swing.JLabel();
        txtState1 = new javax.swing.JTextField();
        lblZipCode1 = new javax.swing.JLabel();
        txtZipCode1 = new javax.swing.JTextField();
        lblPhoneNumber1 = new javax.swing.JLabel();
        txtPhoneNumber1 = new javax.swing.JTextField();
        workAddressJPanel2 = new javax.swing.JPanel();
        lblAddressTitle2 = new javax.swing.JLabel();
        lblStreetAddress2 = new javax.swing.JLabel();
        txtStreetAddress2 = new javax.swing.JTextField();
        lblUnitNumber2 = new javax.swing.JLabel();
        txtUnitNumber2 = new javax.swing.JTextField();
        lblCity2 = new javax.swing.JLabel();
        txtCity2 = new javax.swing.JTextField();
        lblState2 = new javax.swing.JLabel();
        txtState2 = new javax.swing.JTextField();
        lblZipCode2 = new javax.swing.JLabel();
        txtZipCode2 = new javax.swing.JTextField();
        lblPhoneNumber2 = new javax.swing.JLabel();
        txtPhoneNumber2 = new javax.swing.JTextField();
        btnCreatePerson = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblHomeAddressTitle.setText("Home Address");

        lblHomeStreetAddress.setText("Street Address");

        lblHomeUnitNumber.setText("Unit Number");

        lblHomeCity.setText("City");

        lblState.setText("State");

        lblHomeZipCode.setText("Zip Code");

        lblHomePhoneNumber.setText("Phone Number");

        javax.swing.GroupLayout workAddressJPanelLayout = new javax.swing.GroupLayout(workAddressJPanel);
        workAddressJPanel.setLayout(workAddressJPanelLayout);
        workAddressJPanelLayout.setHorizontalGroup(
            workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomeAddressTitle)
                    .addGroup(workAddressJPanelLayout.createSequentialGroup()
                        .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHomeZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHomeCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHomeStreetAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHomeAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtHomeCity)
                            .addComponent(txtHomeZipCode))
                        .addGap(158, 158, 158)
                        .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHomePhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lblHomeUnitNumber)
                            .addComponent(txtHomeUnitNumber)
                            .addComponent(lblState)
                            .addComponent(txtHomeState)
                            .addComponent(lblHomePhoneNumber))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workAddressJPanelLayout.setVerticalGroup(
            workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomeAddressTitle)
                .addGap(18, 18, 18)
                .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeStreetAddress)
                    .addComponent(lblHomeUnitNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeCity)
                    .addComponent(lblState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeZipCode)
                    .addComponent(lblHomePhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        lblTitle.setText("                              CREATE PERSON ");

        lblfirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblAge.setText("Age");

        lblSocialSecurityNumber.setText("SSN");

        txtSocialSecurityNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocialSecurityNumberActionPerformed(evt);
            }
        });

        lblGender.setText("Gender");

        lblBMI.setText("BMI");

        lblHeight.setText("Height");

        homeAddressJPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAddressTitle1.setText("Home Address");

        lblStreetAddress1.setText("Street Address");

        lblUnitNumber1.setText("Unit Number");

        lblCity1.setText("City");

        lblState1.setText("State");

        lblZipCode1.setText("Zip Code");

        lblPhoneNumber1.setText("Phone Number");

        javax.swing.GroupLayout homeAddressJPanel1Layout = new javax.swing.GroupLayout(homeAddressJPanel1);
        homeAddressJPanel1.setLayout(homeAddressJPanel1Layout);
        homeAddressJPanel1Layout.setHorizontalGroup(
            homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddressJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddressTitle1)
                    .addGroup(homeAddressJPanel1Layout.createSequentialGroup()
                        .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblZipCode1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCity1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStreetAddress1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreetAddress1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtCity1)
                            .addComponent(txtZipCode1))
                        .addGap(158, 158, 158)
                        .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhoneNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lblUnitNumber1)
                            .addComponent(txtUnitNumber1)
                            .addComponent(lblState1)
                            .addComponent(txtState1)
                            .addComponent(lblPhoneNumber1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeAddressJPanel1Layout.setVerticalGroup(
            homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddressJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddressTitle1)
                .addGap(18, 18, 18)
                .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress1)
                    .addComponent(lblUnitNumber1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(lblState1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode1)
                    .addComponent(lblPhoneNumber1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeAddressJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        workAddressJPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAddressTitle2.setText("Work Address");

        lblStreetAddress2.setText("Street Address");

        lblUnitNumber2.setText("Unit Number");

        lblCity2.setText("City");

        lblState2.setText("State");

        lblZipCode2.setText("Zip Code");

        lblPhoneNumber2.setText("Phone Number");

        javax.swing.GroupLayout workAddressJPanel2Layout = new javax.swing.GroupLayout(workAddressJPanel2);
        workAddressJPanel2.setLayout(workAddressJPanel2Layout);
        workAddressJPanel2Layout.setHorizontalGroup(
            workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddressJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddressTitle2)
                    .addGroup(workAddressJPanel2Layout.createSequentialGroup()
                        .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblZipCode2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCity2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStreetAddress2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreetAddress2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtCity2)
                            .addComponent(txtZipCode2))
                        .addGap(158, 158, 158)
                        .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhoneNumber2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lblUnitNumber2)
                            .addComponent(txtUnitNumber2)
                            .addComponent(lblState2)
                            .addComponent(txtState2)
                            .addComponent(lblPhoneNumber2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workAddressJPanel2Layout.setVerticalGroup(
            workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddressJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddressTitle2)
                .addGap(18, 18, 18)
                .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress2)
                    .addComponent(lblUnitNumber2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity2)
                    .addComponent(lblState2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode2)
                    .addComponent(lblPhoneNumber2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workAddressJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnCreatePerson.setText("CREATE PERSON");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(229, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreatePerson)
                                .addGap(153, 153, 153)
                                .addComponent(btnBack))
                            .addComponent(workAddressJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeAddressJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAge, lblBMI, lblGender, lblHeight, lblLastName, lblSocialSecurityNumber, lblfirstName, txtAge, txtBMI, txtFirstName, txtGender, txtHeight, txtLastName, txtSocialSecurityNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSocialSecurityNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBMI)
                    .addComponent(lblGender))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(homeAddressJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workAddressJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePerson)
                    .addComponent(btnBack))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAge, lblBMI, lblGender, lblHeight, lblLastName, lblSocialSecurityNumber, lblfirstName, txtAge, txtBMI, txtFirstName, txtGender, txtHeight, txtLastName, txtSocialSecurityNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void txtSocialSecurityNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocialSecurityNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocialSecurityNumberActionPerformed

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        int age ;
        String socialSecurityNumber = txtSocialSecurityNumber.getText();
        String genderInput = txtGender.getText();
        double height;
        float bmi;
        int hunitNumber;
        String hstreetAddress = txtStreetAddress1.getText();
        String hcity = txtCity1.getText();
        String hstate = txtState1.getText();
        String hzipCode = txtZipCode1.getText();
        String hphoneNumber = txtPhoneNumber2.getText();
        String wstreetAddress = txtStreetAddress2.getText();
        int wunitNumber;
        String wcity = txtCity2.getText();
        String wstate = txtState2.getText();
        String wzipCode = txtZipCode2.getText();
        String wphoneNumber = txtPhoneNumber2.getText();
        
        
        try{
            age = Integer.parseInt(txtAge.getText());
            height=Double.parseDouble(txtHeight.getText());
            bmi=Float.parseFloat(txtBMI.getText());
            hunitNumber = Integer.parseInt(txtUnitNumber1.getText());
            wunitNumber = Integer.parseInt(txtUnitNumber2.getText());
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid input", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(firstName.isBlank() || lastName.isBlank() ||  socialSecurityNumber.isBlank() || genderInput.isBlank() || hstreetAddress.isBlank() ||  hcity.isBlank() || hstate.isBlank() || hzipCode.isBlank() || hphoneNumber.isBlank() || wstreetAddress.isBlank() || wcity.isBlank() || wstate.isBlank() || wzipCode.isBlank() || wphoneNumber.isBlank())
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         Character gender = genderInput.charAt(0);
         Person p = personDirectory.addPerson();
         p.setFirstName(firstName);
         p.setLastName(lastName);
         p.setAge(age);
         p.setSocialSecurityNumber(socialSecurityNumber);
         p.setGender(gender);
         p.setHeight(height);
         p.setBmi(bmi);
         Address a = new Address();
         a.setHstreetAddress(hstreetAddress);
         a.setHunitNumber(hunitNumber);
         a.setHcity(hcity);
         a.setHstate(hstate);
         a.setHzipCode(hzipCode);
         a.setHphoneNumber(hphoneNumber);
         a.setWcity(wcity);
         a.setWphoneNumber(wphoneNumber);
         a.setWstate(wstate);
         a.setWunitNumber(wunitNumber);
         a.setWzipCode(wzipCode);
         a.setWstreetAddress(wstreetAddress);
         p.setAddress(a);
         
         
        JOptionPane.showMessageDialog(this, "Person successfully added", "Information", JOptionPane.INFORMATION_MESSAGE);
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtSocialSecurityNumber.setText("");
        txtGender.setText("");
        txtHeight.setText("");
        txtBMI.setText("");
        txtStreetAddress1.setText("");
        txtUnitNumber1.setText("");
        txtCity1.setText("");
        txtState1.setText("");
        txtZipCode1.setText("");
        txtPhoneNumber1.setText("");
        txtStreetAddress2.setText("");
        txtUnitNumber2.setText("");
        txtCity2.setText("");
        txtState2.setText("");
        txtZipCode2.setText("");
        txtPhoneNumber2.setText("");
       
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JPanel homeAddressJPanel1;
    private javax.swing.JLabel lblAddressTitle1;
    private javax.swing.JLabel lblAddressTitle2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBMI;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCity2;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHomeAddressTitle;
    private javax.swing.JLabel lblHomeCity;
    private javax.swing.JLabel lblHomePhoneNumber;
    private javax.swing.JLabel lblHomeStreetAddress;
    private javax.swing.JLabel lblHomeUnitNumber;
    private javax.swing.JLabel lblHomeZipCode;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblPhoneNumber2;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblState1;
    private javax.swing.JLabel lblState2;
    private javax.swing.JLabel lblStreetAddress1;
    private javax.swing.JLabel lblStreetAddress2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnitNumber1;
    private javax.swing.JLabel lblUnitNumber2;
    private javax.swing.JLabel lblZipCode1;
    private javax.swing.JLabel lblZipCode2;
    private javax.swing.JLabel lblfirstName;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBMI;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtCity2;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHomeAddress;
    private javax.swing.JTextField txtHomeCity;
    private javax.swing.JTextField txtHomePhoneNumber;
    private javax.swing.JTextField txtHomeState;
    private javax.swing.JTextField txtHomeUnitNumber;
    private javax.swing.JTextField txtHomeZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber1;
    private javax.swing.JTextField txtPhoneNumber2;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtState1;
    private javax.swing.JTextField txtState2;
    private javax.swing.JTextField txtStreetAddress1;
    private javax.swing.JTextField txtStreetAddress2;
    private javax.swing.JTextField txtUnitNumber1;
    private javax.swing.JTextField txtUnitNumber2;
    private javax.swing.JTextField txtZipCode1;
    private javax.swing.JTextField txtZipCode2;
    private javax.swing.JPanel workAddressJPanel;
    private javax.swing.JPanel workAddressJPanel2;
    // End of variables declaration//GEN-END:variables
}
