/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Varnika Mujumdar
 */
public class ListPersonJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    
    //private JTable listPersonTable;
    //private JScrollPane scrollPaneListPerson;
    

    /**
     * Creates new form ListPersonJPanel
     */
    public ListPersonJPanel(JPanel container , PersonDirectory directory) {
        initComponents();
        this.userProcessContainer = container;
        this.personDirectory = directory;
        populateTable();
        scroll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListPersonTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListPerson = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        lblListPersonTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblListPersonTitle.setText("                                       LIST PERSON");

        tblListPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Age", "SSN", "Gender", "Height", "BMI", "Home Street Address", "Home Unit Number", "Home City", "Home State", "Home Zip Code", "Home Phone Number", "Work Street Address", "Work Unit Number", "Work City", "Work State", "Work Zip Code", "Work Phone Number"
            }
        ));
        jScrollPane1.setViewportView(tblListPerson);

        btnViewDetails.setText("View Details");

        btnDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lblListPersonTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnViewDetails});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblListPersonTitle)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnViewDetails)
                .addGap(32, 32, 32)
                .addComponent(btnDelete)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDelete, btnViewDetails});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListPersonTitle;
    private javax.swing.JTable tblListPerson;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblListPerson.getModel();
        model.setRowCount(0);  
        for(Person p : personDirectory.getPersons()){
            Object [] row = new Object[19];
            row[0]=p.getFirstName();
            row[1]=p.getLastName();
            row[2]=p.getAge();
            row[3]=p.getSocialSecurityNumber();
            row[4]=p.getGender();
            row[5]=p.getHeight();
            row[6]=p.getBmi();
            row[7]=p.getAddress().getHstreetAddress();
            row[8]=p.getAddress().getHunitNumber();
            row[9]=p.getAddress().getHcity();
            row[10]=p.getAddress().getHstate();
            row[11]=p.getAddress().getHzipCode();
            row[12]=p.getAddress().getHphoneNumber();
            row[13]=p.getAddress().getWstreetAddress();
            row[14]=p.getAddress().getWunitNumber();
            row[15]=p.getAddress().getWcity();
            row[16]=p.getAddress().getWstate();
            row[17]=p.getAddress().getWzipCode();
            row[18]=p.getAddress().getWphoneNumber();
             model.addRow(row);
        }
    }
    

    private void scroll() {
       
        tblListPerson.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000,300));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportView(tblListPerson);
    }
}
